// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezkaucgaqlmuwzhgixgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6a2F1Y2dhcWxtdXd6aGdpeGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MTAxODAsImV4cCI6MjA4NjE4NjE4MH0.dxZohYJGYMmweoB3Ugw2o41Yy_MlXmhgm89VYRH3Yew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});