// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdrwrpkswinodyxtaihd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcndycGtzd2lub2R5eHRhaWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MDkwMTksImV4cCI6MjA4NjE4NTAxOX0.70e43Cy78qze4r5ghtTS-JEsW_tiukp0iP174NgqJe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});