// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtknaeiykrfjrzgvskvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0a25hZWl5a3JmanJ6Z3Zza3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMTk0NTQsImV4cCI6MjA4NTg5NTQ1NH0.VgXbpEiwtYqbUhJg6ET4JMrxckjI5tg1m6svQdLbzuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});